### ISSUE TITLE
UFO

### ISSUE THREAD

**Issue by madhead** [madhead/vectors#23]
![believe](https://cloud.githubusercontent.com/assets/577360/25057314/6ec4a7ee-2177-11e7-8879-0d65b4999681.png)

**Comment by jcdenton** [comment]
![Bro](https://fivestonesandasling.files.wordpress.com/2014/11/buddy_christ1.jpg)

**Comment by madhead** [comment]
![image](https://user-images.githubusercontent.com/577360/28676506-772d0232-72f3-11e7-9b15-c525813e34a8.png)
