### ISSUE TITLE
Аист типа

### ISSUE THREAD

**Issue by madhead** [madhead/vectors#26]
![image](https://cloud.githubusercontent.com/assets/577360/26162011/3a6df1c8-3b2e-11e7-862f-d61207b6ff3c.png)
![image](https://cloud.githubusercontent.com/assets/577360/26162023/3ea8e892-3b2e-11e7-893a-2e59289cce4b.png)

**Comment by jcdenton** [comment]
Проиграл с надписи

**Comment by madhead** [comment]
@jcdenton ага, я тож. Но аист прикольный. Можно сделать нечто среднее между аквиллой и аистом. Буит ваще огонь, а?

**Comment by madhead** [comment]
Ох пора б засесть воплощать все эти идеи. А то не репа, а сборник пикч в ишьюсах.

**Comment by jcdenton** [comment]
Ага, некоторые линки уже 404
